### ISSUE TITLE
YAML errors in running handsfree_v6_plus_arm_bringup

### ISSUE THREAD

**Issue by SkyWxxk** [HANDS-FREE/ROS_DEMO#18]
When I running the `roslaunch handsfree_v6_plus_arm_bringup arm_bringup.launch sim:=true` in terminal, the errors occured. Some of errors are below:
`
Traceback (most recent call last):
  File "v6_plus_arm_sim_hw.py", line 4, in <module>
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/__init__.py", line 47, in <module>
    from std_msgs.msg import Header
  File "/opt/ros/noetic/lib/python3/dist-packages/std_msgs/msg/__init__.py", line 1, in <module>
    from ._Bool import *
  File "/opt/ros/noetic/lib/python3/dist-packages/std_msgs/msg/_Bool.py", line 6, in <module>
    import genpy
  File "/opt/ros/noetic/lib/python3/dist-packages/genpy/__init__.py", line 34, in <module>
    from . message import Message, SerializationError, DeserializationError, MessageException, struct_I
  File "/opt/ros/noetic/lib/python3/dist-packages/genpy/message.py", line 48, in <module>
    import yaml
  File "/opt/ros/noetic/lib/python3/dist-packages/yaml/__init__.py", line 399
    class YAMLObject(metaclass=YAMLObjectMetaclass):
                              ^
SyntaxError: invalid syntax
process[arm_action_server-9]: started with pid [14471]
Traceback (most recent call last):
  File "arm_controller_trajectory.py", line 7, in <module>
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/__init__.py", line 47, in <module>
    from std_msgs.msg import Header
  File "/opt/ros/noetic/lib/python3/dist-packages/std_msgs/msg/__init__.py", line 1, in <module>
    from ._Bool import *
  File "/opt/ros/noetic/lib/python3/dist-packages/std_msgs/msg/_Bool.py", line 6, in <module>
    import genpy
  File "/opt/ros/noetic/lib/python3/dist-packages/genpy/__init__.py", line 34, in <module>
    from . message import Message, SerializationError, DeserializationError, MessageException, struct_I
  File "/opt/ros/noetic/lib/python3/dist-packages/genpy/message.py", line 48, in <module>
    import yaml
  File "/opt/ros/noetic/lib/python3/dist-packages/yaml/__init__.py", line 399
    class YAMLObject(metaclass=YAMLObjectMetaclass):
                              ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "joint_state_publisher.py", line 3, in <module>
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/__init__.py", line 47, in <module>
    from std_msgs.msg import Header
  File "/opt/ros/noetic/lib/python3/dist-packages/std_msgs/msg/__init__.py", line 1, in <module>
    from ._Bool import *
  File "/opt/ros/noetic/lib/python3/dist-packages/std_msgs/msg/_Bool.py", line 6, in <module>
    import genpy
  File "/opt/ros/noetic/lib/python3/dist-packages/genpy/__init__.py", line 34, in <module>
    from . message import Message, SerializationError, DeserializationError, MessageException, struct_I
  File "/opt/ros/noetic/lib/python3/dist-packages/genpy/message.py", line 48, in <module>
    import yaml
  File "/opt/ros/noetic/lib/python3/dist-packages/yaml/__init__.py", line 399
    class YAMLObject(metaclass=YAMLObjectMetaclass):
                              ^
SyntaxError: invalid syntax
[v6_plus_arm_sim_hw-2] process has died [pid 14463, exit code 1, cmd /home/nick/handsfree/handsfree_ros_ws/src/handsfree_arm/handsfree_v6_plus_arm/handsfree_v6_plus_arm_hw/scripts/v6_plus_arm_sim_hw.pyc __name:=v6_plus_arm_sim_hw __log:=/home/nick/.ros/log/07dab29e-e26e-11ed-94d5-8d5134ab6ba9/v6_plus_arm_sim_hw-2.log].
log file: /home/nick/.ros/log/07dab29e-e26e-11ed-94d5-8d5134ab6ba9/v6_plus_arm_sim_hw-2*.log
`
These handsfree packages can work in handsfree girreff robot which is ubuntu16 with ros kinetic. I want to run these packages in ubuntu20 with ros noetic. How to fix these problems?

**Comment by yangzhongii** [comment]
May be you should try python2.7, because the packages are designed for ubuntu16 which uses python2. The difference between python2 and python3 may lead to SyntaxError easily.
